name: Publish Package to GitHub NPM Registry

on: 
  release: 
   types: released
  workflow_dispatch:
    
jobs:
    npm-package:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: Install / Setup NodeJS
          uses: actions/setup-node@v4
          with:
            node-version: "2.x"
            registry-url: 'https://npm.pkg.github.com/'
        - name: Install NPM dependencies
          run: npm install


